#:schema node_modules/wrangler/config-schema.json
name = "todo-backend"
main = "src/index.ts"
compatibility_date = "2025-01-12"

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "todo-db"
database_id = "0fb9b5ae-0faa-4023-b40e-991399de146b"
